### PR TITLE
Add Electron compilation instructions

### PR DESCRIPTION
**Pull request by earonesty**

### CODE REVIEW

**Comment by yellowblood** [comment]
That's a bit advanced I'd say. Maybe it should be on a separate file even.

**Comment by Mirobit** [comment]
I agree with @yellowblood. This is to advanced for the average user. It could be mentioned in a sentence as optional, including a link to the ADVANCED.md file.

**Comment by aaronferrucci** [comment]
I like the idea of putting the wallet build instructions on an "advanced" page...

**Comment by yellowblood** [comment]
@earonesty - see my changes, and if you have anything to add

**Comment by earonesty** [comment]
Lgtm.    I agree this is technical, but  I think it's useful to have that info on the same page

**Comment by earonesty** [comment]
Linking  is better, I agree

**Pull request merged**
