### PR TITLE
Some exchanges are accepting BCH

### PR DESCRIPTION
**Pull request by lra**

### CODE REVIEW

**Comment by yellowblood** [comment]
I've heard ViaBTC blocked Bitcoin withdrawals - a dangerous game to play with the guys behind BCash. Does HitBTC allow Bitcoin withdrawals?

**Comment by lra** [comment]
I can remove ViaBTC as I have not tested it.
I did sold and withdrawn from HitBTC, and people I know did too. That's the only legit way to sell BCH right now.

**Comment by Mirobit** [comment]
@yellowblood If you deposited BCH and traded them for BTC you need to wait for 20 BCH blocks since your deposit. So withdrawals aren't blocked in general but so far no one was able to withdrawal since there are only 15 BCH blocks. I will report when the next 5 blocks have been mined if the withdrawal worked.

@lra You can exchange BCH at viabtc after 1 confirmation.

**Comment by yellowblood** [comment]
@Mirobit thanks for the clearing, please have a look at the updated guide and provide feedback (in the form of PRs or Issues).

**Pull request merged**
